language: perl
sudo: false
addons:
  apt:
    packages:
    - aspell
perl:
#  - "5.26"
#  - "5.24"
  - "5.22"
#  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"
#  - "5.8"
env:
  - "TEST_POD=1"
before_install:
  - git clone git://github.com/mohawk2/helpers ~/travis-perl-helpers -b fix-ci
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps
script:
  - make
  - prove -b -j$(test-jobs) $(test-files)   # parallel testing
notifications:
  email: false
